### GET Clientes
GET http://localhost:8080/api/v1/clientes
Content-Type: application/json

### POST Clientes
POST http://localhost:8080/api/v1/clientes
Content-Type: application/json

{ "id":0,
  "nome":"Zezinho",
  "endereco":"Rua lalala 100",
  "telefone":"5555-1234",
  "email":"ze@ze.com",
  "dataNascimento": "2025-09-11"
}


### PUT Clientes
PUT http://localhost:8080/api/v1/clientes/1
Content-Type: application/json

{ 
  "nome":"Zezinho",
  "endereco":"Rua lalala 100",
  "telefone":"5555-1234",
  "email":"ze@ze.com",
  "dataNascimento": "2025-09-11"
}


### DELETE Clientes
DELETE http://localhost:8080/api/v1/clientes/1
Content-Type: application/json